version: '3.10'

services:
  dash_app:
    build: .
    ports:
      - '8050:8050'
    depends_on:
      - api_service

  api_service:
    build:
      context: ./API_testing
      dockerfile: Dockerfile
    image: "py_api"
    ports:
      - '9001:5000'
